/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_api_v1_accounts_get"];
        put?: never;
        /** Create Account */
        post: operations["create_account_api_v1_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Account */
        patch: operations["update_account_api_v1_accounts__account_id__patch"];
        trace?: never;
    };
    "/api/v1/knowledge/strategy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Strategy */
        get: operations["strategy_api_v1_knowledge_strategy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/buildings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buildings */
        get: operations["buildings_api_v1_knowledge_buildings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/buildings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Building */
        get: operations["building_api_v1_knowledge_buildings__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Units */
        get: operations["units_api_v1_knowledge_units_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/units/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unit */
        get: operations["unit_api_v1_knowledge_units__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/guides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Guides */
        get: operations["guides_api_v1_knowledge_guides_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/guides/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Guide */
        get: operations["guide_api_v1_knowledge_guides__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/villages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Villages */
        get: operations["list_villages_api_v1_villages_get"];
        put?: never;
        /** Upsert Village */
        post: operations["upsert_village_api_v1_villages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/villages/{village_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Village */
        get: operations["get_village_api_v1_villages__village_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Village */
        patch: operations["update_village_api_v1_villages__village_id__patch"];
        trace?: never;
    };
    "/api/v1/assistant/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_v1_assistant_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_api_v1_assistant_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop */
        post: operations["stop_api_v1_assistant_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync */
        post: operations["sync_api_v1_assistant_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_v1_game_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/world/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_v1_world_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/world/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nearby */
        get: operations["nearby_api_v1_world_nearby_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/world/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync */
        post: operations["sync_api_v1_world_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_v1_agents_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_v1_agents_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Detail */
        get: operations["run_detail_api_v1_agents_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_v1_agents_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/flow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Flow */
        get: operations["flow_api_v1_agents_flow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Logs */
        get: operations["logs_api_v1_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_v1_game_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config */
        get: operations["config_api_v1_agents_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plans */
        get: operations["plans_api_v1_agents_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_v1_agents_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings_api_v1_agents_settings_patch"];
        trace?: never;
    };
    "/api/v1/agents/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decisions */
        get: operations["decisions_api_v1_agents_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/quests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quests */
        get: operations["quests_api_v1_agents_quests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run */
        post: operations["run_api_v1_agents_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/act": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Act */
        post: operations["act_api_v1_agents_act_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lessons */
        get: operations["lessons_api_v1_agents_lessons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/coordination": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coordination */
        get: operations["coordination_api_v1_agents_coordination_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/coordination/{village_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coordination History */
        get: operations["coordination_history_api_v1_agents_coordination__village_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/villages/{village_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Role */
        put: operations["set_role_api_v1_agents_villages__village_id__role_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/proposers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Proposers */
        get: operations["proposers_api_v1_agents_proposers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Challenges */
        get: operations["challenges_api_v1_challenges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Info */
        get: operations["info_api_v1_system_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIInfo */
        AIInfo: {
            /** Provider */
            provider: string;
            /** Model */
            model: string | null;
            /** Base Url */
            base_url: string | null;
            /** Key Configured */
            key_configured: boolean;
            /** Active */
            active: boolean;
            /** Error */
            error: string | null;
        };
        /** AccountIn */
        AccountIn: {
            /** Name */
            name?: string | null;
            /**
             * World Url
             * @description Ex.: https://br145.tribalwars.com.br
             */
            world_url: string;
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Headless
             * @default false
             */
            headless: boolean;
        };
        /** AccountOut */
        AccountOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Server */
            server: string;
            /** World Url */
            world_url: string;
            /** Username */
            username: string;
            /** Headless */
            headless: boolean;
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AccountUpdate */
        AccountUpdate: {
            /** Name */
            name?: string | null;
            /** Password */
            password?: string | null;
            /** Headless */
            headless?: boolean | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /** AgentActOut */
        AgentActOut: {
            /** Ok */
            ok: boolean;
            /** Dry Run */
            dry_run: boolean;
            /** Detail */
            detail: string;
            /**
             * Data
             * @default {}
             */
            data: {
                [key: string]: unknown;
            };
        };
        /** AgentActRequest */
        AgentActRequest: {
            /** Village Id */
            village_id: number;
            /** Tool */
            tool: string;
            /**
             * Arguments
             * @default {}
             */
            arguments: {
                [key: string]: unknown;
            };
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
            /**
             * Source
             * @description Who asked: api, mcp or web (kept in the decision log).
             * @default api
             */
            source: string;
        };
        /** AgentConfigOut */
        AgentConfigOut: {
            /** Brain */
            brain: string;
            /** Provider */
            provider: string;
            /** Model */
            model: string | null;
            /** Agents */
            agents: {
                [key: string]: unknown;
            }[];
            settings: components["schemas"]["AgentSettings"];
            /** Last Run At */
            last_run_at: string | null;
        };
        /** AgentDecisionOut */
        AgentDecisionOut: {
            /** Id */
            id: number;
            /** Run Id */
            run_id: string;
            /** Village Id */
            village_id: number | null;
            /** Agent */
            agent: string;
            /** Action */
            action: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Ok */
            ok: boolean;
            /** Dry Run */
            dry_run: boolean;
            /** Reason */
            reason: string;
            /** Result */
            result: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AgentRunOut */
        AgentRunOut: {
            /** Run Id */
            run_id: string;
            /** Brain */
            brain: string;
            /** Dry Run */
            dry_run: boolean;
            /** Villages */
            villages?: components["schemas"]["VillageRunOut"][];
            /** Error */
            error?: string | null;
        };
        /** AgentRunRequest */
        AgentRunRequest: {
            /** Dry Run */
            dry_run?: boolean | null;
            /** Village Ids */
            village_ids?: number[] | null;
        };
        /** AgentSettings */
        AgentSettings: {
            /**
             * Enabled
             * @description Run the agents on a schedule inside the server.
             * @default false
             */
            enabled: boolean;
            /**
             * Interval Minutes
             * @description Minutes between scheduled rounds.
             * @default 10
             */
            interval_minutes: number;
            /**
             * Dry Run
             * @description Simulate and log without acting in the game.
             * @default false
             */
            dry_run: boolean;
            /**
             * Auto Finish Free
             * @description Click the free finish-now button on short builds (never paid ones).
             * @default true
             */
            auto_finish_free: boolean;
            /**
             * Llm Agents
             * @description Agents that may call the AI; the rest run on rules.
             */
            llm_agents?: string[];
            /**
             * Plan Refresh Minutes
             * @description Minutes before the strategist rewrites the plan.
             * @default 360
             */
            plan_refresh_minutes: number;
            /**
             * Llm Max Steps
             * @description Tool rounds per AI conversation.
             * @default 6
             */
            llm_max_steps: number;
        };
        /** AgentSettingsUpdate */
        AgentSettingsUpdate: {
            /** Enabled */
            enabled?: boolean | null;
            /** Interval Minutes */
            interval_minutes?: number | null;
            /** Dry Run */
            dry_run?: boolean | null;
            /** Auto Finish Free */
            auto_finish_free?: boolean | null;
            /** Llm Agents */
            llm_agents?: string[] | null;
            /** Plan Refresh Minutes */
            plan_refresh_minutes?: number | null;
            /** Llm Max Steps */
            llm_max_steps?: number | null;
        };
        /** AgentStat */
        AgentStat: {
            /** Agent */
            agent: string;
            /** Actions */
            actions: number;
            /** Ok */
            ok: number;
            /** Refused */
            refused: number;
            /** Failed */
            failed: number;
            /** Last Action */
            last_action: string | null;
            /** Last Result */
            last_result: string | null;
            /** Last At */
            last_at: string | null;
        };
        /** AssistantStatus */
        AssistantStatus: {
            /** Running */
            running: boolean;
            /** Logged In */
            logged_in: boolean;
            /** World */
            world: string;
            /**
             * Scheduler Jobs
             * @default []
             */
            scheduler_jobs: string[];
            /** Last Sync At */
            last_sync_at?: string | null;
            /** Last Error */
            last_error?: string | null;
        };
        /** BuildingOut */
        BuildingOut: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Level */
            level: number;
            /** Max Level */
            max_level: number | null;
            /** Next Level */
            next_level: number | null;
            /** Next Wood */
            next_wood: number | null;
            /** Next Clay */
            next_clay: number | null;
            /** Next Iron */
            next_iron: number | null;
            /** Next Pop */
            next_pop: number | null;
            /** Build Time */
            build_time: number | null;
            /** Can Build */
            can_build: boolean;
            /** Blocker */
            blocker: string | null;
            /** Queued Level */
            queued_level: number | null;
            /** Queued Until */
            queued_until: string | null;
        };
        /** ChallengeOut */
        ChallengeOut: {
            /** Group */
            group: string;
            /** Name */
            name: string;
            /** Tier */
            tier?: string | null;
            /** Level */
            level: number;
            /** Description */
            description: string;
            /** Current */
            current?: number | null;
            /** Target */
            target?: number | null;
            /** Ratio */
            ratio?: number | null;
            /** Earned */
            earned: boolean;
            /** Done */
            done: boolean;
            /** Status */
            status: string;
            /** Agent */
            agent: string;
            /** How */
            how: string;
        };
        /** ChallengesOut */
        ChallengesOut: {
            /** Updated At */
            updated_at?: string | null;
            /** Items */
            items: components["schemas"]["ChallengeOut"][];
            /** Summary */
            summary: {
                [key: string]: number;
            };
        };
        /** CommandOut */
        CommandOut: {
            /** Village Coords */
            village_coords: string;
            /** Direction */
            direction: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Coords */
            coords: string | null;
            /**
             * Arrival At
             * Format: date-time
             */
            arrival_at: string;
        };
        /** CommandResult */
        CommandResult: {
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
        };
        /** CoordinationOut */
        CoordinationOut: {
            /** Run Id */
            run_id: string;
            /** Village Id */
            village_id: number;
            /**
             * Village
             * @default
             */
            village: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Role */
            role: string;
            /** Mode */
            mode: string;
            /** Goal */
            goal: string;
            /** Next Review At */
            next_review_at: string | null;
            /**
             * Manual Role
             * @default false
             */
            manual_role: boolean;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** CountRow */
        CountRow: {
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /** DecisionOut */
        DecisionOut: {
            /** Id */
            id: number;
            /** Village Id */
            village_id: number | null;
            /** Agent */
            agent: string;
            /** Action */
            action: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Ok */
            ok: boolean;
            /** Dry Run */
            dry_run: boolean;
            /** Reason */
            reason: string;
            /** Result */
            result: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FlowLink */
        FlowLink: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Count */
            count: number;
        };
        /** FlowNode */
        FlowNode: {
            /** Id */
            id: string;
            /** Count */
            count: number;
        };
        /** FlowOut */
        FlowOut: {
            /** Calls */
            calls: number;
            /** Runs */
            runs: number;
            /** Agents */
            agents: components["schemas"]["FlowNode"][];
            /** Tools */
            tools: components["schemas"]["FlowNode"][];
            /** Outcomes */
            outcomes: components["schemas"]["FlowNode"][];
            /** Agent Tool */
            agent_tool: components["schemas"]["FlowLink"][];
            /** Tool Outcome */
            tool_outcome: components["schemas"]["FlowLink"][];
        };
        /** GameOverview */
        GameOverview: {
            player: components["schemas"]["PlayerOut"] | null;
            /** Villages */
            villages: components["schemas"]["VillageOverview"][];
            /** Commands */
            commands: components["schemas"]["CommandOut"][];
            /** Reports */
            reports: components["schemas"]["ReportOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** HourBucket */
        HourBucket: {
            /**
             * Hour
             * Format: date-time
             */
            hour: string;
            /** By Agent */
            by_agent: {
                [key: string]: number;
            };
        };
        /** LessonOut */
        LessonOut: {
            /** Key */
            key: string;
            /** Topic */
            topic: string;
            /** Title */
            title: string;
            /** Text */
            text: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Seen */
            seen: number;
            /** Ok */
            ok: number;
            /** Failed */
            failed: number;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
        };
        /** LiveOut */
        LiveOut: {
            /** Running */
            running: boolean;
            /** Run Id */
            run_id?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Village */
            village?: string | null;
            /** Agent */
            agent?: string | null;
            /** Step */
            step?: string | null;
            /** Next Run At */
            next_run_at?: string | null;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
        };
        /** LogOut */
        LogOut: {
            /** Id */
            id: number;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Level */
            level: string;
            /** Source */
            source: string;
            /** Message */
            message: string;
            /** Process */
            process: string;
        };
        /** NearbyVillage */
        NearbyVillage: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Coords */
            coords: string;
            /** Points */
            points: number;
            /** Distance */
            distance: number;
            /** Player Id */
            player_id: number;
            /** Player Name */
            player_name: string | null;
            /** Ally Tag */
            ally_tag: string | null;
            /** Is Barbarian */
            is_barbarian: boolean;
            /** Travel Minutes */
            travel_minutes: {
                [key: string]: number;
            };
        };
        /** PlanStep */
        PlanStep: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "build" | "recruit" | "unlock_scavenge";
            /**
             * Target
             * @description Building id (build), unit id (recruit) or scavenging tier 1-4 (unlock_scavenge).
             */
            target: string;
            /**
             * Amount
             * @description Level to reach (build), troops to have (recruit), 1 for unlock.
             */
            amount: number;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "queued" | "done" | "blocked";
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** PlayerOut */
        PlayerOut: {
            /** Name */
            name: string;
            /** World */
            world: string;
            /** Points */
            points: number;
            /** Rank */
            rank: number;
            /** Villages */
            villages: number;
            /** Incomings */
            incomings: number;
            /** Premium Points */
            premium_points: number;
            /** New Reports */
            new_reports: number;
            /** New Mails */
            new_mails: number;
            /** New Quests */
            new_quests: boolean;
            /** Daily Bonus */
            daily_bonus: boolean;
            /** Protection Until */
            protection_until: string | null;
            /** Synced At */
            synced_at: string | null;
        };
        /** ProposerOut */
        ProposerOut: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            /** Observes */
            observes: string;
            /** Delivers */
            delivers: string;
        };
        /** QuestGoalOut */
        QuestGoalOut: {
            /** Title */
            title: string;
            /** Text */
            text: string;
            /** Current */
            current: number | null;
            /** Target */
            target: number | null;
        };
        /** QuestOut */
        QuestOut: {
            /** Quest Id */
            quest_id: string;
            /** Line Id */
            line_id: string;
            /** Title */
            title: string;
            /** State */
            state: string;
            /** Description */
            description: string;
            /** Goals */
            goals: components["schemas"]["QuestGoalOut"][];
            /** Can Complete */
            can_complete: boolean;
        };
        /** QuestRewardOut */
        QuestRewardOut: {
            /** Reward Id */
            reward_id: string;
            /** Label */
            label: string;
        };
        /** QuestsOut */
        QuestsOut: {
            /** Quests */
            quests: components["schemas"]["QuestOut"][];
            /** Rewards */
            rewards: components["schemas"]["QuestRewardOut"][];
        };
        /** RecommendationOut */
        RecommendationOut: {
            /** Building */
            building: string;
            /** Label */
            label: string;
            /** From Level */
            from_level: number;
            /** To Level */
            to_level: number;
            /** Wood */
            wood: number;
            /** Clay */
            clay: number;
            /** Iron */
            iron: number;
            /** Pop */
            pop: number;
            /** Build Time */
            build_time: number | null;
            /** Can Build */
            can_build: boolean;
            /** Blocker */
            blocker: string | null;
            /** Eta Seconds */
            eta_seconds: number | null;
            /** Priority */
            priority: string;
            /** Reason */
            reason: string;
        };
        /** RecruitOrderOut */
        RecruitOrderOut: {
            /** Unit */
            unit: string;
            /** Count */
            count: number;
            /** Finishes At */
            finishes_at: string | null;
        };
        /** ReportOut */
        ReportOut: {
            /** Game Id */
            game_id: string;
            /** Title */
            title: string;
            /** Category */
            category: string;
            /** Result */
            result: string | null;
            /** Is New */
            is_new: boolean;
            /** Received At */
            received_at: string | null;
            /** Origin Coords */
            origin_coords: string | null;
            /** Target Coords */
            target_coords: string | null;
            /** Loot Wood */
            loot_wood: number;
            /** Loot Clay */
            loot_clay: number;
            /** Loot Iron */
            loot_iron: number;
            /** Haul Total */
            haul_total: number | null;
        };
        /** RoleIn */
        RoleIn: {
            /**
             * Role
             * @description Papel fixo da aldeia; vazio devolve a escolha ao coordenador.
             */
            role?: ("growth" | "defense" | "offensive" | "support" | "expansion") | null;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** RoleOut */
        RoleOut: {
            /** Village Id */
            village_id: number;
            /** Role */
            role: string;
            /** Manual */
            manual: boolean;
            /** Reason */
            reason: string;
        };
        /** RunDetailOut */
        RunDetailOut: {
            run: components["schemas"]["RunOut"];
            /** Villages */
            villages: {
                [key: string]: string;
            };
            /** Steps */
            steps: components["schemas"]["StepOut"][];
            /** Decisions */
            decisions: components["schemas"]["DecisionOut"][];
        };
        /** RunOut */
        RunOut: {
            /** Run Id */
            run_id: string;
            /** Trigger */
            trigger: string;
            /** Status */
            status: string;
            /** Brain */
            brain: string;
            /** Provider */
            provider: string | null;
            /** Model */
            model: string | null;
            /** Dry Run */
            dry_run: boolean;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Villages */
            villages: number;
            /** Actions Ok */
            actions_ok: number;
            /** Actions Refused */
            actions_refused: number;
            /** Actions Failed */
            actions_failed: number;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Error */
            error: string | null;
        };
        /** ScavengeOut */
        ScavengeOut: {
            /** Option Id */
            option_id: number;
            /** Name */
            name: string;
            /** Loot Factor */
            loot_factor: number;
            /** Is Locked */
            is_locked: boolean;
            /** Unlock At */
            unlock_at: string | null;
            /** Return At */
            return_at: string | null;
        };
        /** SnapshotOut */
        SnapshotOut: {
            /** Village Id */
            village_id: number;
            /**
             * Taken At
             * Format: date-time
             */
            taken_at: string;
            /** Points */
            points: number;
            /** Wood */
            wood: number;
            /** Clay */
            clay: number;
            /** Iron */
            iron: number;
            /** Storage */
            storage: number;
            /** Pop Current */
            pop_current: number;
            /** Pop Max */
            pop_max: number;
            /** Troops Home */
            troops_home: number;
            /** Troops Total */
            troops_total: number;
        };
        /** StatsOut */
        StatsOut: {
            /** Hours */
            hours: number;
            /** Runs */
            runs: number;
            /** Runs Failed */
            runs_failed: number;
            /** Actions Ok */
            actions_ok: number;
            /** Actions Refused */
            actions_refused: number;
            /** Actions Failed */
            actions_failed: number;
            /** Attacks */
            attacks: number;
            /** Builds */
            builds: number;
            /** Recruits */
            recruits: number;
            /** Quests */
            quests: number;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Hourly */
            hourly: components["schemas"]["HourBucket"][];
            /** Refusals */
            refusals: components["schemas"]["CountRow"][];
            /** By Action */
            by_action: components["schemas"]["CountRow"][];
            /** Agents */
            agents: components["schemas"]["AgentStat"][];
        };
        /** StepOut */
        StepOut: {
            /** Seq */
            seq: number;
            /** Village Id */
            village_id: number | null;
            /** Agent */
            agent: string;
            /** Kind */
            kind: string;
            /** Tool */
            tool: string | null;
            /** Content */
            content: string;
            /** Is Error */
            is_error: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SystemInfo */
        SystemInfo: {
            /** Version */
            version: string;
            /** World Url */
            world_url: string | null;
            /** Server */
            server: string | null;
            /** Sync Interval Seconds */
            sync_interval_seconds: number;
            /** World Sync Interval Minutes */
            world_sync_interval_minutes: number;
            /** Quiet Hours */
            quiet_hours: string | null;
            /** Headless */
            headless: boolean;
            /** Database */
            database: string;
            /** Log Retention Days */
            log_retention_days: number;
            /** Trace Retention Days */
            trace_retention_days: number;
            ai: components["schemas"]["AIInfo"];
        };
        /** UnitOut */
        UnitOut: {
            /** Name */
            name: string;
            /** Home */
            home: number;
            /** Total */
            total: number;
            /** Away */
            away: number;
            /** Available */
            available: boolean;
            /** Max Recruit */
            max_recruit: number;
            /** Cost Wood */
            cost_wood: number | null;
            /** Cost Clay */
            cost_clay: number | null;
            /** Cost Iron */
            cost_iron: number | null;
            /** Cost Pop */
            cost_pop: number | null;
            /** Build Time */
            build_time: number | null;
            /** Blocker */
            blocker: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Village */
        Village: {
            /** Name */
            name: string;
            /** Coords */
            coords: string;
            /**
             * Is Own
             * @default true
             */
            is_own: boolean;
            /**
             * Wood
             * @default 0
             */
            wood: number;
            /**
             * Clay
             * @default 0
             */
            clay: number;
            /**
             * Iron
             * @default 0
             */
            iron: number;
            /**
             * Storage
             * @default 0
             */
            storage: number;
            /**
             * Pop Current
             * @default 0
             */
            pop_current: number;
            /**
             * Pop Max
             * @default 0
             */
            pop_max: number;
            /** Id */
            id: number;
            /** Game Id */
            game_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** VillageCreate */
        VillageCreate: {
            /** Name */
            name: string;
            /** Coords */
            coords: string;
            /**
             * Is Own
             * @default true
             */
            is_own: boolean;
            /**
             * Wood
             * @default 0
             */
            wood: number;
            /**
             * Clay
             * @default 0
             */
            clay: number;
            /**
             * Iron
             * @default 0
             */
            iron: number;
            /**
             * Storage
             * @default 0
             */
            storage: number;
            /**
             * Pop Current
             * @default 0
             */
            pop_current: number;
            /**
             * Pop Max
             * @default 0
             */
            pop_max: number;
            /** Game Id */
            game_id?: string | null;
        };
        /** VillageOverview */
        VillageOverview: {
            /** Id */
            id: number;
            /** Game Id */
            game_id: string | null;
            /** Name */
            name: string;
            /** Coords */
            coords: string;
            /** Points */
            points: number;
            /** Wood */
            wood: number;
            /** Clay */
            clay: number;
            /** Iron */
            iron: number;
            /** Storage */
            storage: number;
            /** Pop Current */
            pop_current: number;
            /** Pop Max */
            pop_max: number;
            /** Wood Prod */
            wood_prod: number;
            /** Clay Prod */
            clay_prod: number;
            /** Iron Prod */
            iron_prod: number;
            /** Synced At */
            synced_at: string | null;
            /** Buildings */
            buildings: components["schemas"]["BuildingOut"][];
            /** Units */
            units: components["schemas"]["UnitOut"][];
            /** Recruit Orders */
            recruit_orders: components["schemas"]["RecruitOrderOut"][];
            /** Scavenge */
            scavenge: components["schemas"]["ScavengeOut"][];
            /** Recommendations */
            recommendations: components["schemas"]["RecommendationOut"][];
        };
        /** VillagePlanOut */
        VillagePlanOut: {
            /** Village Id */
            village_id: number;
            /** Village */
            village: string;
            /** Summary */
            summary: string;
            /** Source */
            source: string;
            /** Refreshed At */
            refreshed_at: string | null;
            /** Steps */
            steps: components["schemas"]["PlanStep"][];
            /** Done */
            done: number;
            /** Total */
            total: number;
        };
        /** VillageRunOut */
        VillageRunOut: {
            /** Village */
            village: string;
            /** Summaries */
            summaries: {
                [key: string]: string;
            };
        };
        /** VillageUpdate */
        VillageUpdate: {
            /** Wood */
            wood?: number | null;
            /** Clay */
            clay?: number | null;
            /** Iron */
            iron?: number | null;
            /** Storage */
            storage?: number | null;
            /** Pop Current */
            pop_current?: number | null;
            /** Pop Max */
            pop_max?: number | null;
        };
        /** WorldStatus */
        WorldStatus: {
            /** Fetched At */
            fetched_at: string | null;
            /** Villages */
            villages: number;
            /** Players */
            players: number;
            /** Allies */
            allies: number;
            /** Speed */
            speed: number | null;
            /** Unit Speed */
            unit_speed: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_accounts_api_v1_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"][];
                };
            };
        };
    };
    create_account_api_v1_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_account_api_v1_accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    strategy_api_v1_knowledge_strategy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    buildings_api_v1_knowledge_buildings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    building_api_v1_knowledge_buildings__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    units_api_v1_knowledge_units_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    unit_api_v1_knowledge_units__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    guides_api_v1_knowledge_guides_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    guide_api_v1_knowledge_guides__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_villages_api_v1_villages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Village"][];
                };
            };
        };
    };
    upsert_village_api_v1_villages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VillageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Village"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_village_api_v1_villages__village_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                village_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Village"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_village_api_v1_villages__village_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                village_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VillageUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Village"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_v1_assistant_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantStatus"];
                };
            };
        };
    };
    start_api_v1_assistant_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResult"];
                };
            };
        };
    };
    stop_api_v1_assistant_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResult"];
                };
            };
        };
    };
    sync_api_v1_assistant_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResult"];
                };
            };
        };
    };
    overview_api_v1_game_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameOverview"];
                };
            };
        };
    };
    status_api_v1_world_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldStatus"];
                };
            };
        };
    };
    nearby_api_v1_world_nearby_get: {
        parameters: {
            query?: {
                village_id?: number | null;
                kind?: "barbarian" | "player" | "all";
                radius?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbyVillage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_api_v1_world_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldStatus"];
                };
            };
        };
    };
    live_api_v1_agents_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveOut"];
                };
            };
        };
    };
    runs_api_v1_agents_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_detail_api_v1_agents_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_v1_agents_stats_get: {
        parameters: {
            query?: {
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    flow_api_v1_agents_flow_get: {
        parameters: {
            query?: {
                hours?: number;
                run_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logs_api_v1_logs_get: {
        parameters: {
            query?: {
                level?: string;
                limit?: number;
                q?: string | null;
                before_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_v1_game_history_get: {
        parameters: {
            query?: {
                village_id?: number | null;
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    config_api_v1_agents_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentConfigOut"];
                };
            };
        };
    };
    plans_api_v1_agents_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VillagePlanOut"][];
                };
            };
        };
    };
    get_settings_api_v1_agents_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSettings"];
                };
            };
        };
    };
    update_settings_api_v1_agents_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decisions_api_v1_agents_decisions_get: {
        parameters: {
            query?: {
                village_id?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDecisionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quests_api_v1_agents_quests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestsOut"];
                };
            };
        };
    };
    run_api_v1_agents_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    act_api_v1_agents_act_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentActRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentActOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lessons_api_v1_agents_lessons_get: {
        parameters: {
            query?: {
                topic?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coordination_api_v1_agents_coordination_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoordinationOut"][];
                };
            };
        };
    };
    coordination_history_api_v1_agents_coordination__village_id__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                village_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoordinationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_role_api_v1_agents_villages__village_id__role_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                village_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proposers_api_v1_agents_proposers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposerOut"][];
                };
            };
        };
    };
    challenges_api_v1_challenges_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengesOut"];
                };
            };
        };
    };
    info_api_v1_system_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
        };
    };
}
